name = "HydroModels"
uuid = "3bb2d84c-373d-45fe-b371-a5244eeae5e2"
authors = ["Håvard Hvarnes <haavardhvarnes@gmail.com>"]
version = "0.1.0"

[deps]
HydroModelsCore = "35d12705-5efd-4182-93f7-afc386ecd870"
HydroModelsOpt = "3ad2896b-1445-4374-ab33-3e97259a88a5"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
HydroModelsCore = "0.1"
HydroModelsOpt = "0.1"
Reexport = "1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
